timezone: Asia/Tokyo

collections:
  authors:
    output: true

#theme: jekyll-theme-cayman
#theme: jekyll-theme-midnight
#theme: jekyll-theme-slate
#theme: jekyll-theme-minimal

defaults:
  - scope:
      path: ''
      type: 'authors'
    values:
      layout: 'author'
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
  - scope:
      path: ''
    values:
      layout: 'default'

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

permalink: /:categories/:year/:month/:day/

name: Japan Datadog User Group Blog Post
description: User Community Group for Datadog
url: https://jdd-ug.github.io/
